name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up cache for Verilator
      id: cache-verilator
      uses: actions/cache@v3
      with:
        path: |
          /home/verilator
          /usr/bin/verilator
          /usr/local/bin
          /usr/local/lib
        key: ${{ runner.os }}-verilator1-${{ hashFiles('**/install_verilator.sh') }}
        restore-keys: |
          ${{ runner.os }}-verilator1-

    - name: Verify Cache
      run: |
        echo "Checking cached files..."
        ls -la /usr/bin | grep verilator || true
        ls -la /home/verilator || true
        ls -la /usr/local/bin || true
        ls -la /usr/local/lib || true

    - name: Install Verilator if not cached
      if: steps.cache-verilator.outputs.cache-hit != 'true'
      run: |
        sudo apt-get update
        sudo apt-get install -y verilator g++ make yosys
        # Move Verilator to /usr/bin if it's not there by default
        sudo cp /usr/local/bin/verilator* /usr/bin/ || true

    - name: Lint Verilog/SystemVerilog Files
      run: verilator --lint-only code.sv
      
    - name: Compile and Simulate with Verilator
      run: |
        # Step 1: Compile the Verilog files with Verilator
        verilator --cc --sv code.sv --exe --build tb_code.cpp

        # Step 2: Run the compiled simulation and display output in logs
        ./obj_dir/Vcode

    - name: List obj_dir Contents
      run: ls -la ${{ github.workspace }}/obj_dir
